name: firuz_market
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State & utilities
  provider: ^6.0.5
  uuid: ^4.3.3
  intl: ^0.20.2
  cupertino_icons: ^1.0.8

  # Storage & local
  shared_preferences: ^2.2.2
  path_provider: ^2.1.2

  # Firebase (سازگار با Dart 3.9 و Flutter 3.35)
  firebase_core: ^4.2.0
  firebase_auth: ^6.1.1
  cloud_firestore: ^6.0.3
  firebase_storage: ^13.0.3

  # File picker (در صورت نیاز؛ این نسخه با macOS/iOS/Android پایدار است)
  file_picker: ^10.3.3

  # Localization
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # اگر از Flutter gen-l10n استفاده می‌کنی، این گزینه را نگه‌دار
  generate: true

  # تعریف assets به‌صورت پوشه (بدون نیاز به فایل‌های جداگانه)
  assets:
    - assets/images/