// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmdJ1isqYAS1v-bQxopvy8QqQx3yEBLgc',
    appId: '1:202974235575:web:254e4e59ead0d21ea3f632',
    messagingSenderId: '202974235575',
    projectId: 'firuzmarket-54136',
    authDomain: 'firuzmarket-54136.firebaseapp.com',
    storageBucket: 'firuzmarket-54136.appspot.com',
    measurementId: 'G-GE6TJ0Z104',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAT2XHyhfmnhxP6lfnCvIVYs5T-vudqXMo',
    appId: '1:202974235575:android:05313fc41f3b5c57a3f632',
    messagingSenderId: '202974235575',
    projectId: 'firuzmarket-54136',
    storageBucket: 'firuzmarket-54136.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrnHNOGLS1xHQTndHVtM9B5vN0ElKvuck',
    appId: '1:202974235575:ios:276ebe626f2e22fba3f632',
    messagingSenderId: '202974235575',
    projectId: 'firuzmarket-54136',
    storageBucket: 'firuzmarket-54136.appspot.com',
    iosBundleId: 'com.example.firuzMarket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrnHNOGLS1xHQTndHVtM9B5vN0ElKvuck',
    appId: '1:202974235575:ios:276ebe626f2e22fba3f632',
    messagingSenderId: '202974235575',
    projectId: 'firuzmarket-54136',
    storageBucket: 'firuzmarket-54136.appspot.com',
    // ❌ iosBundleId حذف شد
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmdJ1isqYAS1v-bQxopvy8QqQx3yEBLgc',
    appId: '1:202974235575:web:24100fed972f60a8a3f632',
    messagingSenderId: '202974235575',
    projectId: 'firuzmarket-54136',
    authDomain: 'firuzmarket-54136.firebaseapp.com',
    storageBucket: 'firuzmarket-54136.appspot.com',
    measurementId: 'G-DGBXBXRSDM',
  );
}